### ISSUE TITLE
stat()함수 중 시간 관련 정보 조사

### ISSUE THREAD

**Issue by ChangWoo95** [qaqa313a/Project2#1]

**Comment by qaqa313a** [comment]
stat()은 파일의 정보를 가져오는 함수이고 필요한 header file은 
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h> 이다.

필요한 인자는 총 2개로, 파일의 경로인 const char* path과  해당 정보의 구조체를 가리키는 struct stat* buf이다.
시간과 관련된 정보 중, 나중에 가장 최근의 수정시간을 비교하기 위해 time_t st_mtime를 이용하려고 합니다.

**Comment by ChangWoo95** [comment]
stat()은 파일의 정보를 가져오는 함수이고 필요한 header file은
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h> 이다.

필요한 인자는 총 2개로, 파일의 경로인 const char* path과 해당 정보의 구조체를 가리키는 struct stat* buf이다.
시간과 관련된 정보 중, 나중에 가장 최근의 수정시간을 비교하기 위해 time_t st_mtime를 이용하려고 합니다.

**Comment by ChangWoo95** [comment]
localtime()은 time_t형의 값들을 사용할 수 있게 가공하는 함수이고, 
이를 통해 년,월,일,시,분,초 등에 접근할 수 있습니다.

**Comment by ChangWoo95** [comment]
localtime_r()은  localtime()과 비슷하게 동작하지만 결과값을 stack영역에 저장하는 것이 아니라 입력한 인자(구조체 포인터)에 저장하므로 multi-thread환경에서 좋습니다.
