### ISSUE TITLE
파일 수정시간 비교 코드 테스팅

### ISSUE THREAD

**Issue by ChangWoo95** [qaqa313a/Project2#17]
테스트 해봤으나 localtime()이 같은 stack영역을 공유하는 문제가 발생하여서 한 파일의 시간정보가 두 번 나옵니다.

**Comment by Sang-Wook** [comment]
아래 링크를 참고하여 localtime_r() 함수를 사용해보시길 추천합니다.
https://www.it-note.kr/136

**Comment by ChangWoo95** [comment]
감사합니다. localtime_r()을 이용하여서 코드들을 수정하겠습니다.

**Comment by ChangWoo95** [comment]
localtime_r()을 이용한 코딩결과, 테스트가 정상적으로 잘 되는 것을 확인할 수 있었습니다.

**Comment by dnjsgud0625** [comment]
좋은 방법인것 같습니다!
