### ISSUE TITLE
파일정보 받아오기 코드 테스팅

### ISSUE THREAD

**Issue by Sang-Wook** [qaqa313a/Project2#4]

**Comment by Sang-Wook** [comment]
파일크기 비교 코드를 작성하고 테스팅하면서 파일의 정보가 잘 받아져 오는지 테스트해 볼 예정입니다.

**Comment by ChangWoo95** [comment]
테스트한 결과는 잘 나왔는지 궁금합니다.

**Comment by Sang-Wook** [comment]
네. 파일크기 비교 코드 테스팅의 issue에서 언급했듯이, 파일크기 비교 테스팅이 잘 이루어졌고 이를 통해 파일정보를 잘 받아왔음을 확인할 수 있었습니다.
