### ISSUE TITLE
localtime함수 조사

### ISSUE THREAD

**Issue by dnjsgud0625** [qaqa313a/Project2#5]

**Comment by dnjsgud0625** [comment]
localtime함수는 time_t값을 활용할 수 있게 가공시켜주는 함수이다.
time->tm_mon+1을 하면 수정된 날짜가 나오고, time->tm_mday를 하면 수정된 일이 나온다.

**Comment by ChangWoo95** [comment]
혹시 localtime()이용 시, 두 파일의 값 비교가 원활히 되었는지 궁금합니다. 저 같은 경우, localtime()이 같은 stack영역을 공유하는 문제가 있어서 localtime() -> localtime_r()로 변경하였습니다.

**Comment by dnjsgud0625** [comment]
변수를 4개 선언하여 각각의 시간에 대한 값들을 구해냄과 동시에 input하였습니다.

**Comment by ChangWoo95** [comment]
변수 4개를 선언했다는 것이 어떤 것을 선언해서 접근했다는 것인가요?

**Comment by dnjsgud0625** [comment]
int형 변수 4개를 선언한 뒤 각각파일의 시간값들을 담아주었습니다.
