### ISSUE TITLE
stat 구조체 조사

### ISSUE THREAD

**Issue by Sang-Wook** [qaqa313a/Project2#6]

**Comment by Sang-Wook** [comment]
stat 구조체에서 파일크기를 나타내는 off_t형 멤버변수 st_size가 있습니다. 이 변수를 이용하여 파일크기 비교 코드를 작성할 예정입니다.

**Comment by dnjsgud0625** [comment]
off_t형은 출력하면 어떤식으로 출력되나요?

**Comment by Sang-Wook** [comment]
서식문자 %ld로 받아서 출력을 시키면 long형 정수로 출력이 됩니다.
